packages:
  - src/core
  - src/ui/*
  - src/lib/*
  - tests/*
  - dev-servers/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - edgedriver
  - esbuild
  - geckodriver
  - unrs-resolver
